language: android
dist: trusty
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - build-tools-29.0.2
    - android-29
    - extra
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-29
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
script:
  - ./gradlew build check